import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import matter from "gray-matter";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..", "..", "..");
const contentDir = resolve(repoRoot, "content");

const COLLECTIONS = ["tools", "comparisons", "workflows", "learn"] as const;
type Collection = (typeof COLLECTIONS)[number];

type LocaleEntry = {
  code: string;
  is_canonical: boolean;
};

type LocalesFile = {
  default_locale: string;
  locales: LocaleEntry[];
};

type Status = "missing" | "stale";

type QueueItem = {
  slug: string;
  status: Status;
  sourcePath: string;
  targetPath: string;
};

type CollectionQueue = {
  collection: Collection;
  items: QueueItem[];
};

function parseLocaleArg(): string | null {
  const args = process.argv.slice(2);
  for (let i = 0; i < args.length; i += 1) {
    const a = args[i];
    if (a.startsWith("--locale=")) return a.slice("--locale=".length);
    if (a === "--locale" && args[i + 1]) return args[i + 1];
  }
  return null;
}

function loadNonCanonicalLocales(only: string | null): string[] {
  const localesFile = JSON.parse(
    readFileSync(resolve(contentDir, "locales.json"), "utf8")
  ) as LocalesFile;
  const all = localesFile.locales.filter((l) => !l.is_canonical).map((l) => l.code);
  if (!only) return all;
  if (!all.includes(only)) {
    console.error(
      `--locale=${only} is not a non-canonical locale. Known: ${all.join(", ")}`
    );
    process.exit(1);
  }
  return [only];
}

function listEnFiles(collection: Collection): string[] {
  const dir = resolve(contentDir, collection, "en");
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".mdx"))
    .map((f) => resolve(dir, f))
    .sort();
}

export function hashEnBody(enBody: string): string {
  return createHash("sha256").update(enBody, "utf8").digest("hex");
}

function classifyItem(
  collection: Collection,
  enFile: string,
  locale: string
): QueueItem | null {
  const enParsed = matter(readFileSync(enFile, "utf8"));
  const canonicalSlug =
    typeof enParsed.data.canonical_slug === "string"
      ? enParsed.data.canonical_slug
      : basename(enFile, ".mdx");
  const targetFile = resolve(contentDir, collection, locale, `${canonicalSlug}.mdx`);
  const sourceRel = `content/${collection}/en/${basename(enFile)}`;
  const targetRel = `content/${collection}/${locale}/${canonicalSlug}.mdx`;

  if (!existsSync(targetFile)) {
    return {
      slug: canonicalSlug,
      status: "missing",
      sourcePath: sourceRel,
      targetPath: targetRel,
    };
  }

  const enHash = hashEnBody(enParsed.content);
  const targetParsed = matter(readFileSync(targetFile, "utf8"));
  const stored = targetParsed.data.source_sha256;
  if (typeof stored !== "string" || stored !== enHash) {
    return {
      slug: canonicalSlug,
      status: "stale",
      sourcePath: sourceRel,
      targetPath: targetRel,
    };
  }
  return null;
}

function buildQueueForLocale(locale: string): CollectionQueue[] {
  const out: CollectionQueue[] = [];
  for (const collection of COLLECTIONS) {
    const enFiles = listEnFiles(collection);
    const items: QueueItem[] = [];
    for (const enFile of enFiles) {
      const item = classifyItem(collection, enFile, locale);
      if (item) items.push(item);
    }
    items.sort((a, b) => a.slug.localeCompare(b.slug));
    out.push({ collection, items });
  }
  return out;
}

function renderItem(item: QueueItem): string {
  const lines: string[] = [];
  lines.push(`- [ ] **${item.slug}** — \`${item.status}\``);
  lines.push(`  - source: \`${item.sourcePath}\``);
  lines.push(`  - target: \`${item.targetPath}\``);
  return lines.join("\n");
}

function renderQueueFile(locale: string, queue: CollectionQueue[]): string {
  const generated = new Date().toISOString();
  const totalItems = queue.reduce((s, c) => s + c.items.length, 0);
  const missing = queue.reduce(
    (s, c) => s + c.items.filter((i) => i.status === "missing").length,
    0
  );
  const stale = queue.reduce(
    (s, c) => s + c.items.filter((i) => i.status === "stale").length,
    0
  );

  const header = [
    "<!-- Generated by `npm run queue:translations`. Do not edit by hand. -->",
    `# ${locale} translation queue`,
    "",
    `Generated: ${generated}`,
    `Source locale: en → Target locale: ${locale}`,
    `Total items: ${totalItems} (${missing} missing, ${stale} stale)`,
    "",
  ];

  if (totalItems === 0) {
    return (
      header.join("\n") +
      "Queue empty — all content translated and current.\n"
    );
  }

  const sections: string[] = [];
  for (const { collection, items } of queue) {
    if (items.length === 0) continue;
    sections.push(`## ${collection} (${items.length})`);
    sections.push("");
    sections.push(items.map(renderItem).join("\n"));
    sections.push("");
  }

  return header.join("\n") + sections.join("\n");
}

function writeQueueFile(locale: string, content: string): string {
  const filename = `${locale}_TRANSLATION_QUEUE.md`;
  const outPath = resolve(repoRoot, filename);
  writeFileSync(outPath, content, "utf8");
  return filename;
}

function main(): void {
  const onlyLocale = parseLocaleArg();
  const locales = loadNonCanonicalLocales(onlyLocale);
  for (const locale of locales) {
    const queue = buildQueueForLocale(locale);
    const content = renderQueueFile(locale, queue);
    const filename = writeQueueFile(locale, content);
    const total = queue.reduce((s, c) => s + c.items.length, 0);
    console.log(
      total === 0
        ? `✓ ${filename} (queue empty)`
        : `✓ ${filename} (${total} item${total === 1 ? "" : "s"})`
    );
  }
}

const isDirectInvocation =
  process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1]);
if (isDirectInvocation) {
  main();
}
